[package]
name = "gherkin_rust"
version = "0.10.1"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
description = "A pure Rust implementation of the Gherkin (`.feature` file) language for the Cucumber testing framework"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/bbqsrc/gherkin-rust"
documentation = "https://docs.rs/gherkin_rust"
homepage = "https://github.com/bbqsrc/gherkin-rust"
edition = "2018"

[[test]]
name = "cucumber"
harness = false

[dependencies]
textwrap = "0.15"
peg = "0.6.3"
thiserror = "1.0.20"
typed-builder = { version = "0.7.0", optional = true }
serde = { version = "1", optional = true, features = ["derive"] }
juniper = { version = "0.15", optional = true }

[dev-dependencies]
cucumber = { package = "cucumber_rust", version = "0.8.1" }
async-trait = "0.1.40"
futures = "0.3.5"

[build-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
quote = "1"
syn = "1"
heck = "0.4"

[features]
default = ["parser"]
parser = ["typed-builder"]
